all_features = true
exclude_re = [
    "src/api_request/async_funcs/orchestration\\.rs:73:24: replace \\+= with .+ in ApiRequest<P>::send_async",
    "src/api_request/sync_funcs/orchestration\\.rs:65:24: replace \\+= with .+ in ApiRequest<P>::send"
]